name: Deploy PHP App

on:
  push:
    branches:
      - release  # Deploy only when code is pushed to the main branch

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install dependencies (Composer)
        run: composer install --no-dev --prefer-dist --no-progress --no-scripts

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rsync -avz --delete \
              --exclude=".git" \
              --exclude="assets" \
              --exclude="node_modules" \
              --exclude="vendor" \
              ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/srv/data/web/vhosts/partez.net/htdocs/
              