name: Copy files with SCP

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy to Remote Server
      uses: pierrickdelrieu/scp-action
      with:
          host: ${{ secrets.HOST }}
          ssh_username: ${{ secrets.USERNAME }}
          ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
          destination_dir: /srv/data/web/vhosts/partez.net/htdocs/ 
          rm: true
